/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      hideInMenu: true,
      needLogin: false,
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      hideInMenu: true,
      needLogin: false,
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      hideInMenu: true,
      needLogin: false,
      constant: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      needLogin: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true,
      keepAlive: true,
      needLogin: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      hideInMenu: true,
      needLogin: false,
      constant: true
    }
  },
  {
    name: 'personal',
    path: '/personal',
    component: 'layout.base',
    meta: {
      title: 'personal',
      i18nKey: 'route.personal',
      needLogin: true
    },
    children: [
      {
        name: 'personal_approvaltask',
        path: '/personal/approvaltask',
        component: 'view.personal_approvaltask',
        meta: {
          title: 'personal_approvaltask',
          i18nKey: 'route.personal_approvaltask',
          needLogin: true
        }
      },
      {
        name: 'personal_mymessage',
        path: '/personal/mymessage',
        component: 'view.personal_mymessage',
        meta: {
          title: 'personal_mymessage',
          i18nKey: 'route.personal_mymessage',
          needLogin: true
        }
      }
    ]
  }
];
